name: Format Pull Request via Prettier
# Source: https://github.com/dylanirlbeck/tailwind-ppx/blob/master/.github/workflows/lint_pr.yml

on: [pull_request]

jobs:
  lint:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Use the branch commit instead of the PR merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Replace absolute links to Handbook
        uses: jacobtomlinson/gha-find-replace@0.1.4
        with:
          find: "\\]\\(https?://handbook\\.tts\\.gsa\\.gov"
          replace: "]({{site.baseurl}}"
          include: "\\.md"
          exclude: "\\.git/|(README|CONTRIBUTING)\\.md"

      # - name: Commit changes
      #   uses: EndBug/add-and-commit@v7
      #   with:
      #     default_author: github_actions
      #     message: Replace absolute links to Handbook
      #     push: false

      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Format sources files
        run: npm run lint
        # run: |
        #   npm run lint
        #   git add "*.md"

      # - name: Check that all the code is formatted.
      #   run: git diff --exit-code --cached

      - name: Commit changes
        # if: failure()
        id: commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: format files

      # - name: Display status should be clean
      #   if: success()
      #   run: git status

      - uses: actions/github-script@0.3.0
        if: ${{ steps.commit.outputs.committed == 'true' }} # failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `I have formatted the code. Please @${context.actor} pull the last commit before pushing any more changes.`
            });
